config/routes.rb
MusicRoomScoreViewer::Application.routes.draw do
  resources :scores

end

app/models/score.rb
class Score < ActiveRecord::Base
  attr_accessible :arranger, :composer, :description, :index, :kananame, :name, :publisher, :status
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scores }
    end
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
    @score = Score.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/new
  # GET /scores/new.json
  def new
    @score = Score.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/1/edit
  def edit
    @score = Score.find(params[:id])
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(params[:score])

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render json: @score, status: :created, location: @score }
      else
        format.html { render action: "new" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scores/1
  # PUT /scores/1.json
  def update
    @score = Score.find(params[:id])

    respond_to do |format|
      if @score.update_attributes(params[:score])
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score = Score.find(params[:id])
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicRoomScoreViewer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %><br />
    <%= f.number_field :index %>
  </div>
  <div class="field">
    <%= f.label :kananame %><br />
    <%= f.text_field :kananame %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :composer %><br />
    <%= f.text_field :composer %>
  </div>
  <div class="field">
    <%= f.label :arranger %><br />
    <%= f.text_field :arranger %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table>
  <tr>
    <th>Index</th>
    <th>Kananame</th>
    <th>Name</th>
    <th>Composer</th>
    <th>Arranger</th>
    <th>Publisher</th>
    <th>Status</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scores.each do |score| %>
  <tr>
    <td><%= score.index %></td>
    <td><%= score.kananame %></td>
    <td><%= score.name %></td>
    <td><%= score.composer %></td>
    <td><%= score.arranger %></td>
    <td><%= score.publisher %></td>
    <td><%= score.status %></td>
    <td><%= score.description %></td>
    <td><%= link_to 'Show', score %></td>
    <td><%= link_to 'Edit', edit_score_path(score) %></td>
    <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Index:</b>
  <%= @score.index %>
</p>

<p>
  <b>Kananame:</b>
  <%= @score.kananame %>
</p>

<p>
  <b>Name:</b>
  <%= @score.name %>
</p>

<p>
  <b>Composer:</b>
  <%= @score.composer %>
</p>

<p>
  <b>Arranger:</b>
  <%= @score.arranger %>
</p>

<p>
  <b>Publisher:</b>
  <%= @score.publisher %>
</p>

<p>
  <b>Status:</b>
  <%= @score.status %>
</p>

<p>
  <b>Description:</b>
  <%= @score.description %>
</p>


<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>